name: Python Lint and Test (L + T)

run-name: L + T, triggered by ${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Set up Pythotn
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -e .[lint]
      - name: Lint code
        run: ruff check --output-format=github .

test: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -e .[test]    

      - name: Test code
        run: |
          pytest -v     
